# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sub_edit(object):
    def setupUi(self, sub_edit):
        sub_edit.setObjectName("sub_edit")
        sub_edit.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(sub_edit)
        self.centralwidget.setObjectName("centralwidget")
        self.edit_age_textbox = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_age_textbox.setGeometry(QtCore.QRect(200, 320, 151, 22))
        self.edit_age_textbox.setObjectName("edit_age_textbox")
        self.edit_balance_textbox = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_balance_textbox.setGeometry(QtCore.QRect(470, 360, 181, 22))
        self.edit_balance_textbox.setObjectName("edit_balance_textbox")
        self.edit_age_label = QtWidgets.QLabel(self.centralwidget)
        self.edit_age_label.setGeometry(QtCore.QRect(90, 310, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_age_label.setFont(font)
        self.edit_age_label.setObjectName("edit_age_label")
        self.edit_email_label = QtWidgets.QLabel(self.centralwidget)
        self.edit_email_label.setGeometry(QtCore.QRect(90, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_email_label.setFont(font)
        self.edit_email_label.setObjectName("edit_email_label")
        self.edit_phone_label = QtWidgets.QLabel(self.centralwidget)
        self.edit_phone_label.setGeometry(QtCore.QRect(50, 410, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_phone_label.setFont(font)
        self.edit_phone_label.setObjectName("edit_phone_label")
        self.edit_balance_label = QtWidgets.QLabel(self.centralwidget)
        self.edit_balance_label.setGeometry(QtCore.QRect(520, 300, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_balance_label.setFont(font)
        self.edit_balance_label.setObjectName("edit_balance_label")
        self.edit_pass_label = QtWidgets.QLabel(self.centralwidget)
        self.edit_pass_label.setGeometry(QtCore.QRect(70, 240, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_pass_label.setFont(font)
        self.edit_pass_label.setObjectName("edit_pass_label")
        self.edit_phone_textbox = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_phone_textbox.setGeometry(QtCore.QRect(200, 410, 151, 22))
        self.edit_phone_textbox.setObjectName("edit_phone_textbox")
        self.edit_name_textbox = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_name_textbox.setGeometry(QtCore.QRect(200, 70, 151, 22))
        self.edit_name_textbox.setObjectName("edit_name_textbox")
        self.edit_subType_label = QtWidgets.QLabel(self.centralwidget)
        self.edit_subType_label.setGeometry(QtCore.QRect(480, 60, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_subType_label.setFont(font)
        self.edit_subType_label.setObjectName("edit_subType_label")
        self.edit_visa_label = QtWidgets.QLabel(self.centralwidget)
        self.edit_visa_label.setGeometry(QtCore.QRect(500, 190, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_visa_label.setFont(font)
        self.edit_visa_label.setObjectName("edit_visa_label")
        self.edit_email_textbox = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_email_textbox.setGeometry(QtCore.QRect(200, 160, 151, 22))
        self.edit_email_textbox.setObjectName("edit_email_textbox")
        self.edit_subType_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.edit_subType_combobox.setGeometry(QtCore.QRect(500, 120, 111, 22))
        self.edit_subType_combobox.setObjectName("edit_subType_combobox")
        self.edit_name_label = QtWidgets.QLabel(self.centralwidget)
        self.edit_name_label.setGeometry(QtCore.QRect(90, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_name_label.setFont(font)
        self.edit_name_label.setObjectName("edit_name_label")
        self.edit_button = QtWidgets.QPushButton(self.centralwidget)
        self.edit_button.setGeometry(QtCore.QRect(510, 470, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_button.setFont(font)
        self.edit_button.setObjectName("edit_button")
        self.edit_password_textbox = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_password_textbox.setGeometry(QtCore.QRect(200, 240, 151, 22))
        self.edit_password_textbox.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_password_textbox.setObjectName("edit_password_textbox")
        self.edit_visa_textbox = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_visa_textbox.setGeometry(QtCore.QRect(470, 240, 181, 22))
        self.edit_visa_textbox.setObjectName("edit_visa_textbox")
        sub_edit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(sub_edit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        sub_edit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(sub_edit)
        self.statusbar.setObjectName("statusbar")
        sub_edit.setStatusBar(self.statusbar)

        self.retranslateUi(sub_edit)
        QtCore.QMetaObject.connectSlotsByName(sub_edit)

    def retranslateUi(self, sub_edit):
        _translate = QtCore.QCoreApplication.translate
        sub_edit.setWindowTitle(_translate("sub_edit", "MainWindow"))
        self.edit_age_label.setText(_translate("sub_edit", "Age"))
        self.edit_email_label.setText(_translate("sub_edit", "Email"))
        self.edit_phone_label.setText(_translate("sub_edit", "Phone Number"))
        self.edit_balance_label.setText(_translate("sub_edit", "Balance"))
        self.edit_pass_label.setText(_translate("sub_edit", "Password"))
        self.edit_subType_label.setText(_translate("sub_edit", "Subscription Type"))
        self.edit_visa_label.setText(_translate("sub_edit", "Visa Card Info"))
        self.edit_name_label.setText(_translate("sub_edit", "Name"))
        self.edit_button.setText(_translate("sub_edit", "Edit"))


